// ~200 common foods including Indian dishes. Values per listed portion.
export const seedFoods = [
  // --- Indian: breakfast ---
  { name: 'Idli', portion: '2 pieces', calories: 116, protein_g: 4, carbs_g: 23, fat_g: 1, fiber_g: 2, category: 'indian' },
  { name: 'Dosa (plain)', portion: '1 dosa', calories: 168, protein_g: 4, carbs_g: 29, fat_g: 4, fiber_g: 1, category: 'indian' },
  { name: 'Masala Dosa', portion: '1 dosa', calories: 387, protein_g: 9, carbs_g: 57, fat_g: 13, fiber_g: 4, category: 'indian' },
  { name: 'Sambar', portion: '1 cup (240ml)', calories: 101, protein_g: 5, carbs_g: 16, fat_g: 2, fiber_g: 4, category: 'indian' },
  { name: 'Coconut Chutney', portion: '2 tbsp', calories: 60, protein_g: 1, carbs_g: 3, fat_g: 5, fiber_g: 1, category: 'indian' },
  { name: 'Poha', portion: '1 cup', calories: 270, protein_g: 5, carbs_g: 48, fat_g: 6, fiber_g: 2, category: 'indian' },
  { name: 'Upma', portion: '1 cup', calories: 270, protein_g: 6, carbs_g: 42, fat_g: 8, fiber_g: 2, category: 'indian' },
  { name: 'Pongal', portion: '1 cup', calories: 290, protein_g: 8, carbs_g: 45, fat_g: 8, fiber_g: 2, category: 'indian' },
  { name: 'Vada', portion: '1 piece', calories: 97, protein_g: 3, carbs_g: 13, fat_g: 4, fiber_g: 1, category: 'indian' },
  { name: 'Uttapam', portion: '1 piece', calories: 220, protein_g: 6, carbs_g: 32, fat_g: 7, fiber_g: 2, category: 'indian' },
  { name: 'Aloo Paratha', portion: '1 paratha', calories: 320, protein_g: 8, carbs_g: 40, fat_g: 13, fiber_g: 4, category: 'indian' },
  { name: 'Chapati', portion: '1 chapati', calories: 120, protein_g: 3, carbs_g: 18, fat_g: 4, fiber_g: 3, category: 'indian' },
  { name: 'Roti', portion: '1 roti', calories: 120, protein_g: 3, carbs_g: 18, fat_g: 4, fiber_g: 3, category: 'indian' },
  { name: 'Thepla', portion: '1 piece', calories: 150, protein_g: 4, carbs_g: 22, fat_g: 5, fiber_g: 2, category: 'indian' },

  // --- Indian: mains / curries ---
  { name: 'Dal (lentil)', portion: '1 cup', calories: 180, protein_g: 9, carbs_g: 24, fat_g: 4, fiber_g: 6, category: 'indian' },
  { name: 'Dal Tadka', portion: '1 cup', calories: 200, protein_g: 9, carbs_g: 24, fat_g: 6, fiber_g: 6, category: 'indian' },
  { name: 'Dal Makhani', portion: '1 cup', calories: 290, protein_g: 8, carbs_g: 28, fat_g: 15, fiber_g: 5, category: 'indian' },
  { name: 'Chana Masala', portion: '1 cup', calories: 270, protein_g: 11, carbs_g: 38, fat_g: 7, fiber_g: 9, category: 'indian' },
  { name: 'Rajma', portion: '1 cup', calories: 260, protein_g: 11, carbs_g: 36, fat_g: 6, fiber_g: 10, category: 'indian' },
  { name: 'Paneer Butter Masala', portion: '1 cup', calories: 430, protein_g: 16, carbs_g: 18, fat_g: 33, fiber_g: 3, category: 'indian' },
  { name: 'Palak Paneer', portion: '1 cup', calories: 340, protein_g: 14, carbs_g: 16, fat_g: 25, fiber_g: 4, category: 'indian' },
  { name: 'Kadai Paneer', portion: '1 cup', calories: 410, protein_g: 17, carbs_g: 20, fat_g: 30, fiber_g: 3, category: 'indian' },
  { name: 'Matar Paneer', portion: '1 cup', calories: 380, protein_g: 15, carbs_g: 24, fat_g: 26, fiber_g: 5, category: 'indian' },
  { name: 'Chicken Curry', portion: '1 cup', calories: 290, protein_g: 22, carbs_g: 8, fat_g: 18, fiber_g: 2, category: 'indian' },
  { name: 'Butter Chicken', portion: '1 cup', calories: 460, protein_g: 26, carbs_g: 14, fat_g: 33, fiber_g: 1, category: 'indian' },
  { name: 'Chicken Tikka', portion: '4 pieces', calories: 260, protein_g: 30, carbs_g: 6, fat_g: 12, fiber_g: 1, category: 'indian' },
  { name: 'Tandoori Chicken', portion: '1 leg', calories: 260, protein_g: 28, carbs_g: 2, fat_g: 15, fiber_g: 0, category: 'indian' },
  { name: 'Fish Curry', portion: '1 cup', calories: 230, protein_g: 20, carbs_g: 9, fat_g: 12, fiber_g: 2, category: 'indian' },
  { name: 'Mutton Curry', portion: '1 cup', calories: 340, protein_g: 24, carbs_g: 8, fat_g: 24, fiber_g: 2, category: 'indian' },
  { name: 'Biryani (chicken)', portion: '1 plate', calories: 520, protein_g: 22, carbs_g: 67, fat_g: 18, fiber_g: 3, category: 'indian' },
  { name: 'Veg Biryani', portion: '1 plate', calories: 430, protein_g: 9, carbs_g: 64, fat_g: 15, fiber_g: 4, category: 'indian' },
  { name: 'Pulao', portion: '1 cup', calories: 250, protein_g: 5, carbs_g: 40, fat_g: 7, fiber_g: 2, category: 'indian' },
  { name: 'Jeera Rice', portion: '1 cup', calories: 240, protein_g: 5, carbs_g: 40, fat_g: 6, fiber_g: 1, category: 'indian' },
  { name: 'Steamed Rice', portion: '1 cup', calories: 205, protein_g: 4, carbs_g: 45, fat_g: 0, fiber_g: 0, category: 'indian' },
  { name: 'Khichdi', portion: '1 cup', calories: 220, protein_g: 7, carbs_g: 38, fat_g: 4, fiber_g: 3, category: 'indian' },
  { name: 'Bhindi Masala', portion: '1 cup', calories: 180, protein_g: 4, carbs_g: 16, fat_g: 11, fiber_g: 5, category: 'indian' },
  { name: 'Aloo Gobi', portion: '1 cup', calories: 220, protein_g: 5, carbs_g: 28, fat_g: 9, fiber_g: 5, category: 'indian' },
  { name: 'Baingan Bharta', portion: '1 cup', calories: 160, protein_g: 4, carbs_g: 18, fat_g: 9, fiber_g: 6, category: 'indian' },
  { name: 'Gobi Manchurian', portion: '1 cup', calories: 280, protein_g: 6, carbs_g: 32, fat_g: 14, fiber_g: 3, category: 'indian' },
  { name: 'Pav Bhaji', portion: '1 serving', calories: 390, protein_g: 9, carbs_g: 48, fat_g: 17, fiber_g: 6, category: 'indian' },
  { name: 'Chole Bhature', portion: '1 serving', calories: 540, protein_g: 14, carbs_g: 70, fat_g: 22, fiber_g: 8, category: 'indian' },
  { name: 'Samosa', portion: '1 piece', calories: 260, protein_g: 5, carbs_g: 30, fat_g: 13, fiber_g: 2, category: 'indian' },
  { name: 'Kachori', portion: '1 piece', calories: 220, protein_g: 4, carbs_g: 26, fat_g: 11, fiber_g: 1, category: 'indian' },
  { name: 'Pakora', portion: '5 pieces', calories: 250, protein_g: 6, carbs_g: 24, fat_g: 15, fiber_g: 2, category: 'indian' },
  { name: 'Dhokla', portion: '2 pieces', calories: 180, protein_g: 7, carbs_g: 28, fat_g: 4, fiber_g: 2, category: 'indian' },
  { name: 'Khandvi', portion: '4 pieces', calories: 200, protein_g: 6, carbs_g: 26, fat_g: 8, fiber_g: 1, category: 'indian' },
  { name: 'Jalebi', portion: '2 pieces', calories: 300, protein_g: 2, carbs_g: 50, fat_g: 10, fiber_g: 0, category: 'indian' },
  { name: 'Gulab Jamun', portion: '2 pieces', calories: 290, protein_g: 4, carbs_g: 38, fat_g: 13, fiber_g: 0, category: 'indian' },
  { name: 'Rasgulla', portion: '2 pieces', calories: 180, protein_g: 4, carbs_g: 34, fat_g: 3, fiber_g: 0, category: 'indian' },
  { name: 'Rasmalai', portion: '2 pieces', calories: 250, protein_g: 6, carbs_g: 30, fat_g: 11, fiber_g: 0, category: 'indian' },
  { name: 'Kheer', portion: '1 cup', calories: 260, protein_g: 6, carbs_g: 38, fat_g: 9, fiber_g: 1, category: 'indian' },
  { name: 'Lassi (sweet)', portion: '1 glass', calories: 180, protein_g: 5, carbs_g: 28, fat_g: 5, fiber_g: 0, category: 'indian' },
  { name: 'Chaas (buttermilk)', portion: '1 glass', calories: 60, protein_g: 3, carbs_g: 6, fat_g: 2, fiber_g: 0, category: 'indian' },
  { name: 'Masala Chai', portion: '1 cup', calories: 90, protein_g: 3, carbs_g: 12, fat_g: 3, fiber_g: 0, category: 'indian' },
  { name: 'Filter Coffee', portion: '1 cup', calories: 80, protein_g: 3, carbs_g: 10, fat_g: 3, fiber_g: 0, category: 'indian' },
  { name: 'Medu Vada', portion: '2 pieces', calories: 194, protein_g: 6, carbs_g: 26, fat_g: 8, fiber_g: 2, category: 'indian' },
  { name: 'Appam', portion: '2 pieces', calories: 180, protein_g: 4, carbs_g: 36, fat_g: 2, fiber_g: 1, category: 'indian' },
  { name: 'Puttu', portion: '1 cup', calories: 240, protein_g: 5, carbs_g: 46, fat_g: 3, fiber_g: 2, category: 'indian' },
  { name: 'Lemon Rice', portion: '1 cup', calories: 250, protein_g: 5, carbs_g: 40, fat_g: 7, fiber_g: 1, category: 'indian' },
  { name: 'Curd Rice', portion: '1 cup', calories: 220, protein_g: 6, carbs_g: 38, fat_g: 5, fiber_g: 1, category: 'indian' },
  { name: 'Curd (yogurt)', portion: '1 cup', calories: 150, protein_g: 8, carbs_g: 12, fat_g: 7, fiber_g: 0, category: 'indian' },
  { name: 'Paneer (raw)', portion: '100g', calories: 265, protein_g: 18, carbs_g: 3, fat_g: 20, fiber_g: 0, category: 'indian' },
  { name: 'Tofu', portion: '100g', calories: 76, protein_g: 8, carbs_g: 2, fat_g: 5, fiber_g: 1, category: 'indian' },

  // --- Grains / breads ---
  { name: 'White Bread', portion: '1 slice', calories: 80, protein_g: 3, carbs_g: 15, fat_g: 1, fiber_g: 1, category: 'grains' },
  { name: 'Whole Wheat Bread', portion: '1 slice', calories: 80, protein_g: 4, carbs_g: 14, fat_g: 1, fiber_g: 2, category: 'grains' },
  { name: 'Bagel', portion: '1 medium', calories: 270, protein_g: 10, carbs_g: 55, fat_g: 2, fiber_g: 2, category: 'grains' },
  { name: 'Croissant', portion: '1 medium', calories: 230, protein_g: 5, carbs_g: 26, fat_g: 12, fiber_g: 1, category: 'grains' },
  { name: 'Tortilla (flour)', portion: '1 medium', calories: 140, protein_g: 4, carbs_g: 24, fat_g: 4, fiber_g: 1, category: 'grains' },
  { name: 'Oats (cooked)', portion: '1 cup', calories: 150, protein_g: 6, carbs_g: 27, fat_g: 3, fiber_g: 4, category: 'grains' },
  { name: 'Cornflakes', portion: '1 cup', calories: 100, protein_g: 2, carbs_g: 24, fat_g: 0, fiber_g: 1, category: 'grains' },
  { name: 'Muesli', portion: '1 cup', calories: 290, protein_g: 8, carbs_g: 56, fat_g: 4, fiber_g: 6, category: 'grains' },
  { name: 'Granola', portion: '1/2 cup', calories: 220, protein_g: 6, carbs_g: 30, fat_g: 9, fiber_g: 4, category: 'grains' },
  { name: 'Quinoa (cooked)', portion: '1 cup', calories: 220, protein_g: 8, carbs_g: 39, fat_g: 4, fiber_g: 5, category: 'grains' },
  { name: 'Pasta (cooked)', portion: '1 cup', calories: 220, protein_g: 8, carbs_g: 43, fat_g: 1, fiber_g: 3, category: 'grains' },
  { name: 'Spaghetti (cooked)', portion: '1 cup', calories: 220, protein_g: 8, carbs_g: 43, fat_g: 1, fiber_g: 3, category: 'grains' },
  { name: 'Macaroni (cooked)', portion: '1 cup', calories: 220, protein_g: 8, carbs_g: 43, fat_g: 1, fiber_g: 3, category: 'grains' },
  { name: 'Noodles (cooked)', portion: '1 cup', calories: 190, protein_g: 4, carbs_g: 38, fat_g: 1, fiber_g: 2, category: 'grains' },
  { name: 'Couscous (cooked)', portion: '1 cup', calories: 180, protein_g: 6, carbs_g: 36, fat_g: 1, fiber_g: 2, category: 'grains' },
  { name: 'Naan', portion: '1 naan', calories: 260, protein_g: 9, carbs_g: 45, fat_g: 5, fiber_g: 2, category: 'grains' },
  { name: 'Baguette', portion: '1 slice', calories: 100, protein_g: 3, carbs_g: 19, fat_g: 1, fiber_g: 1, category: 'grains' },

  // --- Proteins ---
  { name: 'Chicken Breast (grilled)', portion: '100g', calories: 165, protein_g: 31, carbs_g: 0, fat_g: 3.6, fiber_g: 0, category: 'protein' },
  { name: 'Chicken Thigh', portion: '100g', calories: 209, protein_g: 26, carbs_g: 0, fat_g: 11, fiber_g: 0, category: 'protein' },
  { name: 'Chicken Wing', portion: '1 wing', calories: 43, protein_g: 4, carbs_g: 0, fat_g: 3, fiber_g: 0, category: 'protein' },
  { name: 'Ground Beef (85% lean)', portion: '100g', calories: 250, protein_g: 26, carbs_g: 0, fat_g: 17, fiber_g: 0, category: 'protein' },
  { name: 'Steak (sirloin)', portion: '100g', calories: 210, protein_g: 26, carbs_g: 0, fat_g: 13, fiber_g: 0, category: 'protein' },
  { name: 'Pork Chop', portion: '100g', calories: 230, protein_g: 26, carbs_g: 0, fat_g: 14, fiber_g: 0, category: 'protein' },
  { name: 'Bacon', portion: '2 slices', calories: 90, protein_g: 6, carbs_g: 0, fat_g: 7, fiber_g: 0, category: 'protein' },
  { name: 'Ham', portion: '2 slices', calories: 70, protein_g: 11, carbs_g: 1, fat_g: 2, fiber_g: 0, category: 'protein' },
  { name: 'Sausage', portion: '1 link', calories: 150, protein_g: 8, carbs_g: 2, fat_g: 12, fiber_g: 0, category: 'protein' },
  { name: 'Salmon (baked)', portion: '100g', calories: 180, protein_g: 22, carbs_g: 0, fat_g: 10, fiber_g: 0, category: 'protein' },
  { name: 'Tuna (canned)', portion: '100g', calories: 110, protein_g: 24, carbs_g: 0, fat_g: 1, fiber_g: 0, category: 'protein' },
  { name: 'Cod (baked)', portion: '100g', calories: 90, protein_g: 20, carbs_g: 0, fat_g: 1, fiber_g: 0, category: 'protein' },
  { name: 'Shrimp (cooked)', portion: '100g', calories: 99, protein_g: 24, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'protein' },
  { name: 'Egg (whole)', portion: '1 large', calories: 72, protein_g: 6, carbs_g: 0, fat_g: 5, fiber_g: 0, category: 'protein' },
  { name: 'Egg White', portion: '1 large', calories: 17, protein_g: 4, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'protein' },
  { name: 'Omelette (2 egg)', portion: '1 omelette', calories: 180, protein_g: 13, carbs_g: 1, fat_g: 13, fiber_g: 0, category: 'protein' },
  { name: 'Tofu (firm)', portion: '100g', calories: 144, protein_g: 17, carbs_g: 3, fat_g: 9, fiber_g: 2, category: 'protein' },
  { name: 'Tempeh', portion: '100g', calories: 192, protein_g: 20, carbs_g: 8, fat_g: 11, fiber_g: 0, category: 'protein' },
  { name: 'Lentils (cooked)', portion: '1 cup', calories: 230, protein_g: 18, carbs_g: 40, fat_g: 1, fiber_g: 16, category: 'protein' },
  { name: 'Chickpeas (cooked)', portion: '1 cup', calories: 269, protein_g: 15, carbs_g: 45, fat_g: 4, fiber_g: 13, category: 'protein' },
  { name: 'Black Beans', portion: '1 cup', calories: 227, protein_g: 15, carbs_g: 41, fat_g: 1, fiber_g: 15, category: 'protein' },
  { name: 'Kidney Beans', portion: '1 cup', calories: 225, protein_g: 15, carbs_g: 40, fat_g: 1, fiber_g: 13, category: 'protein' },
  { name: 'Pinto Beans', portion: '1 cup', calories: 245, protein_g: 15, carbs_g: 45, fat_g: 1, fiber_g: 15, category: 'protein' },
  { name: 'Edamame', portion: '1 cup', calories: 190, protein_g: 17, carbs_g: 14, fat_g: 8, fiber_g: 8, category: 'protein' },

  // --- Dairy ---
  { name: 'Milk (whole)', portion: '1 cup', calories: 150, protein_g: 8, carbs_g: 12, fat_g: 8, fiber_g: 0, category: 'dairy' },
  { name: 'Milk (skim)', portion: '1 cup', calories: 83, protein_g: 8, carbs_g: 12, fat_g: 0, fiber_g: 0, category: 'dairy' },
  { name: 'Milk (2%)', portion: '1 cup', calories: 120, protein_g: 8, carbs_g: 12, fat_g: 5, fiber_g: 0, category: 'dairy' },
  { name: 'Greek Yogurt', portion: '1 cup', calories: 100, protein_g: 17, carbs_g: 6, fat_g: 0, fiber_g: 0, category: 'dairy' },
  { name: 'Yogurt (plain)', portion: '1 cup', calories: 150, protein_g: 8, carbs_g: 12, fat_g: 8, fiber_g: 0, category: 'dairy' },
  { name: 'Cheddar Cheese', portion: '1 slice', calories: 113, protein_g: 7, carbs_g: 0, fat_g: 9, fiber_g: 0, category: 'dairy' },
  { name: 'Mozzarella', portion: '1 slice', calories: 85, protein_g: 6, carbs_g: 1, fat_g: 6, fiber_g: 0, category: 'dairy' },
  { name: 'Parmesan', portion: '1 tbsp', calories: 22, protein_g: 2, carbs_g: 0, fat_g: 1, fiber_g: 0, category: 'dairy' },
  { name: 'Cottage Cheese', portion: '1 cup', calories: 180, protein_g: 22, carbs_g: 6, fat_g: 5, fiber_g: 0, category: 'dairy' },
  { name: 'Cream Cheese', portion: '2 tbsp', calories: 100, protein_g: 2, carbs_g: 2, fat_g: 10, fiber_g: 0, category: 'dairy' },
  { name: 'Butter', portion: '1 tbsp', calories: 102, protein_g: 0, carbs_g: 0, fat_g: 12, fiber_g: 0, category: 'dairy' },
  { name: 'Ghee', portion: '1 tbsp', calories: 112, protein_g: 0, carbs_g: 0, fat_g: 13, fiber_g: 0, category: 'dairy' },
  { name: 'Paneer', portion: '100g', calories: 265, protein_g: 18, carbs_g: 3, fat_g: 20, fiber_g: 0, category: 'dairy' },

  // --- Fruits ---
  { name: 'Apple', portion: '1 medium', calories: 95, protein_g: 0, carbs_g: 25, fat_g: 0, fiber_g: 4, category: 'fruit' },
  { name: 'Banana', portion: '1 medium', calories: 105, protein_g: 1, carbs_g: 27, fat_g: 0, fiber_g: 3, category: 'fruit' },
  { name: 'Orange', portion: '1 medium', calories: 62, protein_g: 1, carbs_g: 15, fat_g: 0, fiber_g: 3, category: 'fruit' },
  { name: 'Strawberries', portion: '1 cup', calories: 49, protein_g: 1, carbs_g: 12, fat_g: 0, fiber_g: 3, category: 'fruit' },
  { name: 'Blueberries', portion: '1 cup', calories: 84, protein_g: 1, carbs_g: 21, fat_g: 0, fiber_g: 4, category: 'fruit' },
  { name: 'Grapes', portion: '1 cup', calories: 104, protein_g: 1, carbs_g: 27, fat_g: 0, fiber_g: 1, category: 'fruit' },
  { name: 'Mango', portion: '1 cup', calories: 99, protein_g: 1, carbs_g: 25, fat_g: 1, fiber_g: 3, category: 'fruit' },
  { name: 'Pineapple', portion: '1 cup', calories: 82, protein_g: 1, carbs_g: 22, fat_g: 0, fiber_g: 2, category: 'fruit' },
  { name: 'Watermelon', portion: '1 cup', calories: 46, protein_g: 1, carbs_g: 12, fat_g: 0, fiber_g: 1, category: 'fruit' },
  { name: 'Papaya', portion: '1 cup', calories: 55, protein_g: 1, carbs_g: 14, fat_g: 0, fiber_g: 3, category: 'fruit' },
  { name: 'Pear', portion: '1 medium', calories: 101, protein_g: 1, carbs_g: 27, fat_g: 0, fiber_g: 6, category: 'fruit' },
  { name: 'Peach', portion: '1 medium', calories: 59, protein_g: 1, carbs_g: 14, fat_g: 0, fiber_g: 2, category: 'fruit' },
  { name: 'Kiwi', portion: '1 medium', calories: 42, protein_g: 1, carbs_g: 10, fat_g: 0, fiber_g: 2, category: 'fruit' },
  { name: 'Avocado', portion: '1/2 medium', calories: 160, protein_g: 2, carbs_g: 9, fat_g: 15, fiber_g: 7, category: 'fruit' },
  { name: 'Pomegranate', portion: '1/2 cup', calories: 72, protein_g: 1, carbs_g: 16, fat_g: 1, fiber_g: 3, category: 'fruit' },
  { name: 'Guava', portion: '1 medium', calories: 37, protein_g: 1, carbs_g: 8, fat_g: 0, fiber_g: 3, category: 'fruit' },

  // --- Vegetables ---
  { name: 'Broccoli', portion: '1 cup', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 1, fiber_g: 5, category: 'vegetable' },
  { name: 'Carrot', portion: '1 medium', calories: 25, protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 2, category: 'vegetable' },
  { name: 'Spinach (cooked)', portion: '1 cup', calories: 41, protein_g: 5, carbs_g: 7, fat_g: 1, fiber_g: 4, category: 'vegetable' },
  { name: 'Lettuce', portion: '1 cup', calories: 5, protein_g: 0, carbs_g: 1, fat_g: 0, fiber_g: 1, category: 'vegetable' },
  { name: 'Tomato', portion: '1 medium', calories: 22, protein_g: 1, carbs_g: 5, fat_g: 0, fiber_g: 1, category: 'vegetable' },
  { name: 'Cucumber', portion: '1 cup', calories: 16, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1, category: 'vegetable' },
  { name: 'Potato (baked)', portion: '1 medium', calories: 161, protein_g: 4, carbs_g: 37, fat_g: 0, fiber_g: 4, category: 'vegetable' },
  { name: 'Sweet Potato', portion: '1 medium', calories: 103, protein_g: 2, carbs_g: 24, fat_g: 0, fiber_g: 4, category: 'vegetable' },
  { name: 'Onion', portion: '1 medium', calories: 44, protein_g: 1, carbs_g: 10, fat_g: 0, fiber_g: 2, category: 'vegetable' },
  { name: 'Bell Pepper', portion: '1 medium', calories: 31, protein_g: 1, carbs_g: 7, fat_g: 0, fiber_g: 3, category: 'vegetable' },
  { name: 'Cauliflower', portion: '1 cup', calories: 27, protein_g: 2, carbs_g: 5, fat_g: 0, fiber_g: 2, category: 'vegetable' },
  { name: 'Green Beans', portion: '1 cup', calories: 44, protein_g: 2, carbs_g: 10, fat_g: 0, fiber_g: 4, category: 'vegetable' },
  { name: 'Peas', portion: '1 cup', calories: 134, protein_g: 9, carbs_g: 25, fat_g: 1, fiber_g: 9, category: 'vegetable' },
  { name: 'Corn', portion: '1 cup', calories: 132, protein_g: 5, carbs_g: 29, fat_g: 2, fiber_g: 4, category: 'vegetable' },
  { name: 'Mushroom', portion: '1 cup', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1, category: 'vegetable' },
  { name: 'Zucchini', portion: '1 cup', calories: 20, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1, category: 'vegetable' },
  { name: 'Eggplant', portion: '1 cup', calories: 20, protein_g: 1, carbs_g: 5, fat_g: 0, fiber_g: 3, category: 'vegetable' },
  { name: 'Okra (bhindi)', portion: '1 cup', calories: 33, protein_g: 2, carbs_g: 8, fat_g: 0, fiber_g: 3, category: 'vegetable' },

  // --- Snacks / sweets ---
  { name: 'Chocolate Bar', portion: '1 bar', calories: 230, protein_g: 3, carbs_g: 26, fat_g: 13, fiber_g: 2, category: 'snack' },
  { name: 'Cookies', portion: '2 pieces', calories: 160, protein_g: 2, carbs_g: 22, fat_g: 8, fiber_g: 1, category: 'snack' },
  { name: 'Potato Chips', portion: '1 oz', calories: 152, protein_g: 2, carbs_g: 15, fat_g: 10, fiber_g: 1, category: 'snack' },
  { name: 'Popcorn', portion: '1 cup', calories: 31, protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 1, category: 'snack' },
  { name: 'Pretzels', portion: '1 oz', calories: 108, protein_g: 3, carbs_g: 22, fat_g: 1, fiber_g: 1, category: 'snack' },
  { name: 'Ice Cream', portion: '1/2 cup', calories: 137, protein_g: 2, carbs_g: 16, fat_g: 7, fiber_g: 0, category: 'snack' },
  { name: 'Donut', portion: '1 piece', calories: 250, protein_g: 4, carbs_g: 31, fat_g: 14, fiber_g: 1, category: 'snack' },
  { name: 'Muffin', portion: '1 medium', calories: 340, protein_g: 5, carbs_g: 56, fat_g: 11, fiber_g: 2, category: 'snack' },
  { name: 'Brownie', portion: '1 piece', calories: 240, protein_g: 3, carbs_g: 36, fat_g: 11, fiber_g: 1, category: 'snack' },
  { name: 'Cake (slice)', portion: '1 slice', calories: 320, protein_g: 4, carbs_g: 50, fat_g: 13, fiber_g: 1, category: 'snack' },
  { name: 'Dark Chocolate', portion: '1 oz', calories: 155, protein_g: 2, carbs_g: 13, fat_g: 12, fiber_g: 2, category: 'snack' },
  { name: 'Granola Bar', portion: '1 bar', calories: 120, protein_g: 3, carbs_g: 18, fat_g: 5, fiber_g: 1, category: 'snack' },
  { name: 'Trail Mix', portion: '1/4 cup', calories: 175, protein_g: 5, carbs_g: 17, fat_g: 11, fiber_g: 2, category: 'snack' },
  { name: 'Popcorn (buttered)', portion: '1 cup', calories: 55, protein_g: 1, carbs_g: 6, fat_g: 3, fiber_g: 1, category: 'snack' },

  // --- Nuts / seeds ---
  { name: 'Almonds', portion: '1 oz (23)', calories: 164, protein_g: 6, carbs_g: 6, fat_g: 14, fiber_g: 3, category: 'nuts' },
  { name: 'Walnuts', portion: '1 oz', calories: 185, protein_g: 4, carbs_g: 4, fat_g: 18, fiber_g: 2, category: 'nuts' },
  { name: 'Cashews', portion: '1 oz', calories: 157, protein_g: 5, carbs_g: 9, fat_g: 12, fiber_g: 1, category: 'nuts' },
  { name: 'Peanuts', portion: '1 oz', calories: 161, protein_g: 7, carbs_g: 5, fat_g: 14, fiber_g: 2, category: 'nuts' },
  { name: 'Peanut Butter', portion: '2 tbsp', calories: 188, protein_g: 8, carbs_g: 6, fat_g: 16, fiber_g: 2, category: 'nuts' },
  { name: 'Pistachios', portion: '1 oz', calories: 159, protein_g: 6, carbs_g: 8, fat_g: 13, fiber_g: 3, category: 'nuts' },
  { name: 'Chia Seeds', portion: '1 oz', calories: 138, protein_g: 5, carbs_g: 12, fat_g: 9, fiber_g: 10, category: 'nuts' },
  { name: 'Flax Seeds', portion: '1 tbsp', calories: 55, protein_g: 2, carbs_g: 3, fat_g: 4, fiber_g: 3, category: 'nuts' },
  { name: 'Sunflower Seeds', portion: '1 oz', calories: 165, protein_g: 6, carbs_g: 7, fat_g: 14, fiber_g: 3, category: 'nuts' },

  // --- Beverages ---
  { name: 'Coffee (black)', portion: '1 cup', calories: 2, protein_g: 0, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Latte (whole milk)', portion: '12 oz', calories: 180, protein_g: 10, carbs_g: 18, fat_g: 7, fiber_g: 0, category: 'beverage' },
  { name: 'Cappuccino', portion: '12 oz', calories: 120, protein_g: 7, carbs_g: 12, fat_g: 4, fiber_g: 0, category: 'beverage' },
  { name: 'Tea (black)', portion: '1 cup', calories: 2, protein_g: 0, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Green Tea', portion: '1 cup', calories: 2, protein_g: 0, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Orange Juice', portion: '1 cup', calories: 112, protein_g: 2, carbs_g: 26, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Apple Juice', portion: '1 cup', calories: 114, protein_g: 0, carbs_g: 28, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Soda (cola)', portion: '12 oz', calories: 140, protein_g: 0, carbs_g: 39, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Diet Soda', portion: '12 oz', calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Beer', portion: '12 oz', calories: 153, protein_g: 2, carbs_g: 13, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Wine (red)', portion: '5 oz', calories: 125, protein_g: 0, carbs_g: 4, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Wine (white)', portion: '5 oz', calories: 121, protein_g: 0, carbs_g: 4, fat_g: 0, fiber_g: 0, category: 'beverage' },
  { name: 'Smoothie (fruit)', portion: '16 oz', calories: 260, protein_g: 4, carbs_g: 60, fat_g: 1, fiber_g: 5, category: 'beverage' },
  { name: 'Protein Shake', portion: '1 scoop', calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1, fiber_g: 0, category: 'beverage' },
  { name: 'Coconut Water', portion: '1 cup', calories: 46, protein_g: 2, carbs_g: 9, fat_g: 0, fiber_g: 3, category: 'beverage' },

  // --- Fast food / restaurant ---
  { name: 'Cheeseburger', portion: '1 burger', calories: 300, protein_g: 15, carbs_g: 30, fat_g: 14, fiber_g: 1, category: 'fastfood' },
  { name: 'Double Cheeseburger', portion: '1 burger', calories: 540, protein_g: 30, carbs_g: 39, fat_g: 28, fiber_g: 2, category: 'fastfood' },
  { name: 'French Fries', portion: 'medium', calories: 365, protein_g: 4, carbs_g: 48, fat_g: 17, fiber_g: 4, category: 'fastfood' },
  { name: 'Pizza (cheese)', portion: '1 slice', calories: 285, protein_g: 12, carbs_g: 36, fat_g: 10, fiber_g: 2, category: 'fastfood' },
  { name: 'Pizza (pepperoni)', portion: '1 slice', calories: 300, protein_g: 13, carbs_g: 36, fat_g: 12, fiber_g: 2, category: 'fastfood' },
  { name: 'Hot Dog', portion: '1 hot dog', calories: 290, protein_g: 10, carbs_g: 23, fat_g: 17, fiber_g: 1, category: 'fastfood' },
  { name: 'Taco', portion: '1 taco', calories: 170, protein_g: 8, carbs_g: 13, fat_g: 10, fiber_g: 3, category: 'fastfood' },
  { name: 'Burrito', portion: '1 burrito', calories: 620, protein_g: 25, carbs_g: 75, fat_g: 24, fiber_g: 10, category: 'fastfood' },
  { name: 'Fried Chicken', portion: '1 piece', calories: 320, protein_g: 22, carbs_g: 12, fat_g: 20, fiber_g: 0, category: 'fastfood' },
  { name: 'Sushi Roll', portion: '6 pieces', calories: 250, protein_g: 9, carbs_g: 38, fat_g: 7, fiber_g: 1, category: 'fastfood' },
  { name: 'Ramen', portion: '1 bowl', calories: 436, protein_g: 12, carbs_g: 60, fat_g: 16, fiber_g: 3, category: 'fastfood' },
  { name: 'Pad Thai', portion: '1 plate', calories: 510, protein_g: 20, carbs_g: 60, fat_g: 22, fiber_g: 4, category: 'fastfood' },

  // --- Misc / condiments ---
  { name: 'White Rice (cooked)', portion: '1 cup', calories: 205, protein_g: 4, carbs_g: 45, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Brown Rice (cooked)', portion: '1 cup', calories: 216, protein_g: 5, carbs_g: 45, fat_g: 2, fiber_g: 4, category: 'other' },
  { name: 'Honey', portion: '1 tbsp', calories: 64, protein_g: 0, carbs_g: 17, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Sugar', portion: '1 tsp', calories: 16, protein_g: 0, carbs_g: 4, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Olive Oil', portion: '1 tbsp', calories: 119, protein_g: 0, carbs_g: 0, fat_g: 14, fiber_g: 0, category: 'other' },
  { name: 'Ketchup', portion: '1 tbsp', calories: 15, protein_g: 0, carbs_g: 4, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Mayonnaise', portion: '1 tbsp', calories: 90, protein_g: 0, carbs_g: 0, fat_g: 10, fiber_g: 0, category: 'other' },
  { name: 'Mustard', portion: '1 tsp', calories: 5, protein_g: 0, carbs_g: 1, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Soy Sauce', portion: '1 tbsp', calories: 8, protein_g: 1, carbs_g: 1, fat_g: 0, fiber_g: 0, category: 'other' },
  { name: 'Salad Dressing', portion: '2 tbsp', calories: 100, protein_g: 0, carbs_g: 4, fat_g: 10, fiber_g: 0, category: 'other' },
  { name: 'Dark Chocolate (70%)', portion: '1 oz', calories: 170, protein_g: 2, carbs_g: 13, fat_g: 12, fiber_g: 3, category: 'other' }
];
